return {
	 {"--color-main-bg", "#E8E7E1"},
	 {"--color-main-fg", "#02004f"},
	 {"--color-link-visited-bg", "--color-main-bg"},
	 {"--color-link-visited-fg", "#800080"},
	 {"--color-link-bg", "--color-main-bg"},
	 {"--color-link-fg", "#00F"},
	 {"--color-output-border", "#d0cac3"},
	 {"--color-output-bg", "#FFFEF5"},
	 {"--color-output-fg", "#02004f"},
	 {"--color-link-output-visited-bg", "--color-output-bg"},
	 {"--color-link-output-visited-fg", "--color-link-visited-fg"},
	 {"--color-link-output-bg", "--color-output-bg"},
	 {"--color-link-output-fg", "--color-link-fg"},
	 {"--color-error-bg", "--color-output-bg"},
	 {"--color-error-fg", "#E00000"},
}
